-- 1. Profiles Table (Safe to re-run)
create table if not exists profiles (
  id uuid references auth.users not null primary key,
  updated_at timestamp with time zone,
  username text unique,
  email text unique,
  constraint username_length check (char_length(username) >= 3)
);

alter table profiles enable row level security;

-- Drop policies if they exist to avoid error
drop policy if exists "Public profiles are viewable by everyone." on profiles;
drop policy if exists "Users can insert their own profile." on profiles;
drop policy if exists "Users can update own profile." on profiles;

create policy "Public profiles are viewable by everyone." on profiles for select using ( true );
create policy "Users can insert their own profile." on profiles for insert with check ( auth.uid() = id );
create policy "Users can update own profile." on profiles for update using ( auth.uid() = id );


-- 2. Debts Table
create table if not exists debts (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  name text not null,
  type text not null,
  balance numeric not null,
  interest_rate numeric not null,
  min_payment_type text not null,
  min_payment_value numeric not null,
  due_day integer not null,
  status text not null,
  target_payment numeric,
  fixed_payment numeric,
  notes text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table debts enable row level security;

drop policy if exists "Users can view own debts" on debts;
drop policy if exists "Users can insert own debts" on debts;
drop policy if exists "Users can update own debts" on debts;
drop policy if exists "Users can delete own debts" on debts;

create policy "Users can view own debts" on debts for select using (auth.uid() = user_id);
create policy "Users can insert own debts" on debts for insert with check (auth.uid() = user_id);
create policy "Users can update own debts" on debts for update using (auth.uid() = user_id);
create policy "Users can delete own debts" on debts for delete using (auth.uid() = user_id);


-- 3. Budgets Table
create table if not exists budgets (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  salary numeric not null default 0,
  tax numeric not null default 0,
  sso numeric not null default 0,
  pvd numeric not null default 0,
  other_income numeric not null default 0,
  monthly_savings_target numeric not null default 0,
  expenses_json jsonb not null default '{}'::jsonb,
  bonus_json jsonb not null default '[]'::jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table budgets enable row level security;

drop policy if exists "Users can view own budgets" on budgets;
drop policy if exists "Users can insert own budgets" on budgets;
drop policy if exists "Users can update own budgets" on budgets;
drop policy if exists "Users can delete own budgets" on budgets;

create policy "Users can view own budgets" on budgets for select using (auth.uid() = user_id);
create policy "Users can insert own budgets" on budgets for insert with check (auth.uid() = user_id);
create policy "Users can update own budgets" on budgets for update using (auth.uid() = user_id);
create policy "Users can delete own budgets" on budgets for delete using (auth.uid() = user_id);


-- 4. Payment Plans Table
create table if not exists payment_plans (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  strategy text not null default 'snowball',
  allocation_type text,
  allocation_value numeric,
  extra_income_allocation_type text,
  extra_income_allocation_value numeric,
  custom_order integer[],
  bonus_months_json jsonb default '[]'::jsonb,
  min_payment_buffer numeric default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table payment_plans enable row level security;

drop policy if exists "Users can view own plans" on payment_plans;
drop policy if exists "Users can insert own plans" on payment_plans;
drop policy if exists "Users can update own plans" on payment_plans;
drop policy if exists "Users can delete own plans" on payment_plans;

create policy "Users can view own plans" on payment_plans for select using (auth.uid() = user_id);
create policy "Users can insert own plans" on payment_plans for insert with check (auth.uid() = user_id);
create policy "Users can update own plans" on payment_plans for update using (auth.uid() = user_id);
create policy "Users can delete own plans" on payment_plans for delete using (auth.uid() = user_id);


-- 5. Transactions Table
create table if not exists transactions (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  debt_id bigint references debts(id) on delete cascade,
  amount numeric not null,
  date timestamp with time zone not null,
  type text not null,
  note text,
  attachment_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table transactions enable row level security;

drop policy if exists "Users can view own transactions" on transactions;
drop policy if exists "Users can insert own transactions" on transactions;
drop policy if exists "Users can update own transactions" on transactions;
drop policy if exists "Users can delete own transactions" on transactions;

create policy "Users can view own transactions" on transactions for select using (auth.uid() = user_id);
create policy "Users can insert own transactions" on transactions for insert with check (auth.uid() = user_id);
create policy "Users can update own transactions" on transactions for update using (auth.uid() = user_id);
create policy "Users can delete own transactions" on transactions for delete using (auth.uid() = user_id);

