"use client";

import { createContext, useContext, useEffect, useState } from "react";

type Language = 'en' | 'th';

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string, defaultText?: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
    const [language, setLanguageState] = useState<Language>('en');

    useEffect(() => {
        const saved = localStorage.getItem('app-language') as Language;
        if (saved && saved === 'en') {
            setLanguageState(saved);
        } else {
            // Default to English even if Thai was saved, as per user request
            setLanguageState('en');
        }
    }, []);

    const setLanguage = (lang: Language) => {
        setLanguageState(lang);
        localStorage.setItem('app-language', lang);
    };

    const translations: Record<Language, Record<string, string>> = {
        en: {
            "Total Debt": "Total Debt",
            "Monthly Pay": "Monthly Pay",
            "Interest": "Interest",
            "Payoff Date": "Payoff Date",
            "Dashboard": "Dashboard",
            "Payments": "Payments",
            "Debts": "Debts",
            "Plan": "Plan",
            "Scenarios": "Scenarios",
            "Settings": "Settings",
            "Appearance": "Appearance",
            "Language": "Language",
            "Currency": "Currency",
            "Security": "Security",
            "User Profile": "User Profile",
            "Manage your account settings": "Manage your account settings",
            "Customize the look and feel": "Customize the look and feel",
            "Select Language": "Select Language",
            "Select Currency": "Select Currency",
            "Apply Preferences": "Apply Preferences",
            "Sign Out": "Sign Out",
            "Timeline": "Timeline",
            "Debt Distribution": "Debt Distribution",
            "Overview": "Overview",
            "Budget": "Budget",
            "Monthly Plan": "Monthly Plan",
            "Payment History": "Payment History",
            "Burn Down": "Burn Down",
            "Import/Export": "Import/Export",
            "Net Monthly Income": "Net Monthly Income",
            "Fixed Expenses": "Fixed Expenses",
            "Min Debt Payments": "Min Debt Payments",
            "Free Cash Flow": "Free Cash Flow",
            "Principal remaining": "Principal remaining",
            "After tax & deductions": "After tax & deductions",
            "Living costs & commitments": "Living costs & commitments",
            "Required to maintain credit": "Required to maintain credit",
            "Available for snowball/saving": "Available for snowball/saving",
            "Upcoming Payments": "Upcoming Payments",
            "Due within 30 days": "Due within 30 days",
            "No due dates found": "No due dates found",
            "Assign due dates": "Assign due dates in 'Debts' to see them here.",
            "Paid": "Paid",
            "Pay": "Pay",
            "Log Payment": "Log Payment",
            "Due": "Due",
            "Track your monthly obligations.": "Track your monthly obligations.",
            "All caught up!": "All caught up!",
            "No accounts found. Add one to get started.": "No accounts found. Add one to get started.",
            "Are you sure?": "Are you sure?",
            "This action cannot be undone. This will permanently delete the debt account.": "This action cannot be undone. This will permanently delete the debt account.",
            "Cancel": "Cancel",
            "Delete": "Delete",
            "Account Name": "Account Name",
            "Type": "Type",
            "Balance": "Balance",
            "Due Day": "Due Day",
            "Status": "Status",
            "Record Payment": "Record Payment",
            "View History": "View History",
            "Actions": "Actions",
            "Edit": "Edit",
            "Transaction History": "Transaction History",
            "History for": "History for",
            "Date": "Date",
            "Note": "Note",
            "Amount": "Amount",
            "No transactions found.": "No transactions found.",
            "Delete Transaction?": "Delete Transaction?",
            "This will permanently delete this record and": "This will permanently delete this record and",
            "add": "add",
            "back": "back",
            "to your debt balance.": "to your debt balance.",
            "Delete & Revert": "Delete & Revert",
            "Log a payment for": "Log a payment for",
            "This will deduct from the current balance.": "This will deduct from the current balance.",
            "Note (Optional)": "Note (Optional)",
            "Confirm Payment": "Confirm Payment",
            "e.g. February Installment": "e.g. February Installment",
            "Debt updated successfully": "Debt updated successfully",
            "You must be logged in to add a debt": "You must be logged in to add a debt",
            "Debt added successfully": "Debt added successfully",
            "Failed to save debt": "Failed to save debt",
            "Edit Debt": "Edit Debt",
            "Add New Debt": "Add New Debt",
            "Update the details of your debt account.": "Update the details of your debt account.",
            "Enter the details of your debt account here.": "Enter the details of your debt account here.",
            "Add Debt": "Add Debt",
            "Update": "Update",
            "Save Access": "Save",
            "Name must be at least 2 characters.": "Name must be at least 2 characters.",
            "Credit Card": "Credit Card",
            "Personal Loan": "Personal Loan",
            "PayLater": "PayLater",
            "Car Loan": "Car Loan",
            "Motorcycle Loan": "Motorcycle Loan",
            "Bank Loan": "Bank Loan",
            "Other": "Other",
            "Select type": "Select type",
            "Interest (%)": "Interest (%)",
            "Min Pay Type": "Min Pay Type",
            "Method": "Method", // "Type" context for dropdown placeholder
            "% of Balance": "% of Balance",
            "Fixed Amount": "Fixed Amount",
            "Min Value": "Min Value",
            "e.g. KBank Credit Card": "e.g. KBank Credit Card",
            "Application Language": "Application Language",
            "Select your preferred language for the interface.": "Select your preferred language for the interface.",
            "Select your preferred currency for display.": "Select your preferred currency for display.",
            "English (English)": "English (English)",
            "Thai (ไทย)": "Thai (ไทย)",
            "Debt Burn Down": "Debt Burn Down",
            "Projected vs. Actual debt reduction over time.": "Projected vs. Actual debt reduction over time.",
            "No data available for Burn Down Chart.": "No data available for Burn Down Chart.",
            "Projected Balance": "Projected Balance",
            "Actual Balance": "Actual Balance",
            "No debts added yet.": "No debts added yet.",
            "You must be logged in to update records": "You must be logged in to update records",
            "Transaction updated successfully": "Transaction updated successfully",
            "Failed to update transaction": "Failed to update transaction",
            "Edit Transaction": "Edit Transaction",
            "Update payment details for": "Update payment details for",
            "Save Changes": "Save Changes",
            "Payment note": "Payment note",
            "Accumulated Cash": "Accumulated Cash",
            "Compare Scenarios": "Compare Scenarios",
            "Scenario A": "Scenario A",
            "Scenario B": "Scenario B",
            "Debt Free Date": "Debt Free Date",
            "Total Interest": "Total Interest",
            "Money Saved": "Money Saved",
            "Time Saved": "Time Saved",
            "Simulate different financial situations and strategies.": "Simulate different financial situations and strategies."
        },
        th: {
            "Total Debt": "หนี้สินรวม",
            "Monthly Pay": "จ่ายรายเดือน",
            "Interest": "ดอกเบี้ย",
            "Payoff Date": "วันที่หมดหนี้",
            "Dashboard": "แดชบอร์ด",
            "Payments": "ชำระเงิน",
            "Debts": "หนี้สิน",
            "Plan": "แผนชำระ",
            "Scenarios": "จำลองสถานการณ์",
            "Settings": "ตั้งค่า",
            "Appearance": "รูปลักษณ์",
            "Language": "ภาษา",
            "Currency": "สกุลเงิน",
            "Security": "ความปลอดภัย",
            "User Profile": "โปรไฟล์ผู้ใช้",
            "Manage your account settings": "จัดการการตั้งค่าบัญชีของคุณ",
            "Customize the look and feel": "ปรับแต่งรูปลักษณ์และการใช้งาน",
            "Select Language": "เลือกภาษา",
            "Select Currency": "เลือกสกุลเงิน",
            "Apply Preferences": "บันทึกการตั้งค่า",
            "Sign Out": "ออกจากระบบ",
            "Timeline": "ไทม์ไลน์",
            "Debt Distribution": "สัดส่วนหนี้สิน",
            "Overview": "ภาพรวม",
            "Budget": "งบประมาณ",
            "Monthly Plan": "แผนรายเดือน",
            "Payment History": "ประวัติการชำระ",
            "Burn Down": "กราฟลดหนี้",
            "Import/Export": "นำเข้า/ส่งออก",
            "Net Monthly Income": "รายได้สุทธิ",
            "Fixed Expenses": "รายจ่ายคงที่",
            "Min Debt Payments": "ชำระขั้นต่ำ",
            "Free Cash Flow": "เงินเหลือเก็บ",
            "Principal remaining": "เงินต้นคงเหลือ",
            "After tax & deductions": "หลังหักภาษีและรายการหัก",
            "Living costs & commitments": "ค่าใช้จ่ายและภาระผูกพัน",
            "Required to maintain credit": "ที่ต้องจ่ายเพื่อรักษาเครดิต",
            "Available for snowball/saving": "เหลือสำหรับโปะหนี้/ออม",
            "Upcoming Payments": "ยอดที่ต้องชำระเร็วๆ นี้",
            "Due within 30 days": "ครบกำหนดภายใน 30 วัน",
            "No due dates found": "ไม่พบวันครบกำหนดชำระ",
            "Assign due dates": "กำหนดวันครบกำหนดใน 'หนี้สิน' เพื่อดูที่นี่",
            "Paid": "ชำระแล้ว",
            "Pay": "ชำระ",
            "Log Payment": "บันทึกการชำระ",
            "Due": "ครบกำหนด",
            "Track your monthly obligations.": "ติดตามภาระผูกพันรายเดือนของคุณ",
            "All caught up!": "ชำระครบหมดแล้ว!",
            "No accounts found. Add one to get started.": "ไม่พบบัญชีหนี้สิน เพิ่มรายการแรกเพื่อเริ่มต้น",
            "Are you sure?": "คุณแน่ใจหรือไม่?",
            "This action cannot be undone. This will permanently delete the debt account.": "การดำเนินการนี้ไม่สามารถย้อนกลับได้ บัญชีหนี้สินนี้จะถูกลบถาวร",
            "Cancel": "ยกเลิก",
            "Delete": "ลบ",
            "Account Name": "ชื่อบัญชี",
            "Type": "ประเภท",
            "Balance": "ยอดคงเหลือ",
            "Due Day": "วันครบกำหนด",
            "Status": "สถานะ",
            "Record Payment": "บันทึกการชำระ",
            "View History": "ดูประวัติ",
            "Actions": "การจัดการ",
            "Edit": "แก้ไข",
            "Transaction History": "ประวัติธุรกรรม",
            "History for": "ประวัติสำหรับ",
            "Date": "วันที่",
            "Note": "บันทึก ช่วยจำ",
            "Amount": "จำนวนเงิน",
            "No transactions found.": "ไม่พบรายการธุรกรรม",
            "Delete Transaction?": "ลบรายการธุรกรรม?",
            "This will permanently delete this record and": "รายการนี้จะถูกลบถาวรและ",
            "add": "คืนเงิน",
            "back": "กลับ",
            "to your debt balance.": "เข้ายอดหนี้คงเหลือ",
            "Delete & Revert": "ลบและคืนเงิน",
            "Log a payment for": "บันทึกการชำระเงินสำหรับ",
            "This will deduct from the current balance.": "ยอดนี้จะถูกหักออกจากยอดคงเหลือปัจจุบัน",
            "Note (Optional)": "บันทึก (ระบุหรือไม่ก็ได้)",
            "Confirm Payment": "ยืนยันการชำระเงิน",
            "e.g. February Installment": "เช่น ค่างวดเดือนกุมภาพันธ์",
            "Debt updated successfully": "อัปเดตข้อมูลหนี้สินเรียบร้อยแล้ว",
            "You must be logged in to add a debt": "คุณต้องเข้าสู่ระบบเพื่อเพิ่มหนี้สิน",
            "Debt added successfully": "เพิ่มหนี้สินเรียบร้อยแล้ว",
            "Failed to save debt": "บันทึกข้อมูลหนี้สินไม่สำเร็จ",
            "Edit Debt": "แก้ไขหนี้สิน",
            "Add New Debt": "เพิ่มหนี้สินใหม่",
            "Update the details of your debt account.": "อัปเดตรายละเอียดบัญชีหนี้สินของคุณ",
            "Enter the details of your debt account here.": "กรอกรายละเอียดบัญชีหนี้สินของคุณที่นี่",
            "Add Debt": "เพิ่มหนี้สิน",
            "Update": "อัปเดต",
            "Save Access": "บันทึก",
            "Name must be at least 2 characters.": "ชื่อต้องมีความยาวอย่างน้อย 2 ตัวอักษร",
            "Credit Card": "บัตรเครดิต",
            "Personal Loan": "สินเชื่อส่วนบุคคล",
            "PayLater": "บริการ PayLater",
            "Car Loan": "สินเชื่อรถยนต์",
            "Motorcycle Loan": "สินเชื่อรถมอเตอร์ไซค์",
            "Bank Loan": "สินเชื่อธนาคาร",
            "Other": "อื่นๆ",
            "Select type": "เลือกประเภท",
            "Interest (%)": "ดอกเบี้ย (%)",
            "Min Pay Type": "ประเภทการจ่ายขั้นต่ำ",
            "Method": "ประเภท",
            "% of Balance": "% ของยอดคงเหลือ",
            "Fixed Amount": "ยอดคงที่",
            "Min Value": "ยอดขั้นต่ำ",
            "e.g. KBank Credit Card": "เช่น บัตรเครดิต KBank",
            "Application Language": "ภาษาของแอปพลิเคชัน",
            "Select your preferred language for the interface.": "เลือกภาษาที่คุณต้องการสำหรับหน้าจอการใช้งาน",
            "Select your preferred currency for display.": "เลือกสกุลเงินที่คุณต้องการแสดงผล",
            "English (English)": "English (ภาษาอังกฤษ)",
            "Thai (ไทย)": "Thai (ภาษาไทย)",
            "Debt Burn Down": "กราฟลดหนี้",
            "Projected vs. Actual debt reduction over time.": "แผนการลดหนี้เปรียบเทียบกับความเป็นจริง",
            "No data available for Burn Down Chart.": "ไม่มีข้อมูลสำหรับกราฟลดหนี้",
            "Projected Balance": "ยอดคงเหลือตามแผน",
            "Actual Balance": "ยอดคงเหลือจริง",
            "No debts added yet.": "ยังไม่มีรายการหนี้สิน",
            "You must be logged in to update records": "คุณต้องเข้าสู่ระบบเพื่ออัปเดตข้อมูล",
            "Transaction updated successfully": "อัปเดตรายการธุรกรรมเรียบร้อยแล้ว",
            "Failed to update transaction": "อัปเดตรายการธุรกรรมไม่สำเร็จ",
            "Edit Transaction": "แก้ไขรายการธุรกรรม",
            "Update payment details for": "อัปเดตรายละเอียดการชำระเงินสำหรับ",
            "Save Changes": "บันทึกการเปลี่ยนแปลง",
            "Payment note": "บันทึกช่วยจำการชำระเงิน",
            "Accumulated Cash": "เงินสดสะสม",
            "Compare Scenarios": "เปรียบเทียบแผน",
            "Scenario A": "แผน A",
            "Scenario B": "แผน B",
            "Debt Free Date": "วันที่หมดหนี้",
            "Total Interest": "ดอกเบี้ยรวม",
            "Money Saved": "ประหยัดเงินได้",
            "Time Saved": "ประหยัดเวลาได้",
            "Simulate different financial situations and strategies.": "จำลองสถานการณ์และกลยุทธ์ทางการเงินที่แตกต่างกัน"
        }
    };

    const t = (key: string, defaultText?: string) => {
        return translations[language][key] || defaultText || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error("useLanguage must be used within a LanguageProvider");
    }
    return context;
};
